---
- name: clear messages
  ansible.netcommon.telnet:
    port: "{{ hostvars['localhost']['nodes_inventory']['nodes_inventory'][inventory_hostname]['console_port'] }}"
    timeout: 5
    send_newline: true
    clrf: true
    prompts:
      - "['>','#','?']"
    command:
      - show
  register: show

- name: Configure hostname
  telnetX:
    port: "{{ hostvars['localhost']['nodes_inventory']['nodes_inventory'][inventory_hostname]['console_port'] }}"
    timeout: 5
    send_carriage_return: true
    prompts:
      - "['>','#','?']"
    command:
      - configure terminal
      - hostname {{ inventory_hostname }}

- name: Configure con 0
  telnetX:
    port: "{{ hostvars['localhost']['nodes_inventory']['nodes_inventory'][inventory_hostname]['console_port'] }}"
    timeout: 5
    send_carriage_return: true
    prompts:
      - "['>','#','?']"
    command:
      - configure terminal
      - service password-encryption
      - line con 0
      - transport preferred none
      - exec-timeout 0 0
      - privilege level 15
      - logging synchronous
      - length 60
      - width 200
      - exit
  register: con0

- name: Debug con0
  ansible.builtin.debug:
    var: con0

- name: Configure banners
  telnetX:
    port: "{{ hostvars['localhost']['nodes_inventory']['nodes_inventory'][inventory_hostname]['console_port'] }}"
    timeout: 5
    send_carriage_return: true
    prompts:
      - "['>','#','?']"
    command:
      - configure terminal
      - banner exec $$
      - banner incoming $$
      - banner login $$
      - banner motd $$

- name: Configure Interfaces - disable MOP / keepalives
  telnetX:
    port: "{{ hostvars['localhost']['nodes_inventory']['nodes_inventory'][inventory_hostname]['console_port'] }}"
    timeout: 5
    send_carriage_return: true
    remote_user: ""
    password: ""
    prompts:
      - "['>','#','?']"
    command:
      - configure terminal
      - interface r g0/0-3
      - no mop enabled
      - no keepalive
      - exit

- name: Configure SSH
  telnetX:
    port: "{{ hostvars['localhost']['nodes_inventory']['nodes_inventory'][inventory_hostname]['console_port'] }}"
    timeout: 5
    send_carriage_return: true
    prompts:
      - "['>','#','?']"
    command:
      - configure terminal
      - ip domain-name NET.LAB
      - crypto key generate rsa modulus 768
      - username admin password admin
      - line vty 0 4
      - transport input ssh
      - login local
      - exit

- name: Save Config
  telnetX:
    port: "{{ hostvars['localhost']['nodes_inventory']['nodes_inventory'][inventory_hostname]['console_port'] }}"
    timeout: 5
    send_carriage_return: true
    prompts:
      - "['>','#','?']"
    command:
      - copy running-config startup-config
      - "\r"
      - "\r"
