#### GNS3 Server settings
gns3_url: "http://198.18.1.200"
project_name: "GNS3fy_Ansible"
projects_path: "/opt/gns3/projects/"

### Nodes attributes and specifications
gns3_nodes_spec:
  - name: R1
    template: "IOSv"
    x: 0
    y: -150
  - name: "R2"
    template: "IOSv"
    x: -175
    y: 0
  - name: "R3"
    template: "IOSv"
    x: 175
    y: 0
  - name: "GNSMgmt"
    template: "GNSMgmt"
    x: -50
    y: -300

### Links mapping
gns3_links_spec:
  - ["R1", "Gi0/1", "R2", "Gi0/1"]
  - ["R1", "Gi0/2", "R3", "Gi0/1"]
  - ["R2", "Gi0/2", "R3", "Gi0/2"]
  - ["R1", "Gi0/0", "GNSMgmt", "eth2"]
