all:
  hosts:
    R1:
      ansible_host: 198.18.1.200
      device_type: "cisco_ios_telnet"
    R2:
      ansible_host: 198.18.1.200
      device_type: "cisco_ios_telnet"
    R3:
      ansible_host: 198.18.1.200
      device_type: "cisco_ios_telnet"
