### Main playbook to setup or teardown a lab
- name: Lab creation
  import_playbook: lab_build.yml
  when: execute == "build"

- name: Lab destruction
  import_playbook: lab_destroy.yml
  when: execute == "destroy"
