- hosts: localhost
  gather_facts: false
  vars_files:
    - inventory/gns3_vars.yml

  collections:
    - davidban77.gns3
  tasks:
    - name: "Verify version of GNS3 server"
      gns3_version:
        url: "{{ gns3_url }}"
      register: version
    - debug: var=version

    - name: "Create network topology"
      gns3_project:
        url: "{{ gns3_url }}"
        project_name: "{{ project_name }}"
        project_path: "/opt/gns3/projects/{{ project_name }}"
        scene_height: 500
        scene_width: 500
        state: present
        nodes_spec: "{{ gns3_nodes_spec }}"
        links_spec: "{{ gns3_links_spec }}"

    - name: "Start nodes"
      gns3_project:
        url: "{{ gns3_url }}"
        project_name: "GNS3Fy_Ansible"
        state: opened
        nodes_state: started
        nodes_strategy: one_by_one
