---
- name: Play for creating GNS3 Projects
  hosts: localhost
  gather_facts: false
  vars_files:
    - inventory/gns3_vars.yml
  tasks:
    - name: "Verify version of GNS3 server"
      davidban77.gns3.gns3_version:
        url: "{{ gns3_url }}"
      register: version

    - name: "Debug Version"
      ansible.builtin.debug:
        var: version

    - name: "Create network topology"
      davidban77.gns3.gns3_project:
        url: "{{ gns3_url }}"
        project_name: "{{ project_name }}"
        project_path: "{{ projects_path }}{{ project_name }}"
        scene_height: 550
        scene_width: 550
        state: present
        nodes_spec: "{{ gns3_nodes_spec }}"
        links_spec: "{{ gns3_links_spec }}"

    - name: "Start nodes"
      davidban77.gns3.gns3_project:
        url: "{{ gns3_url }}"
        project_name: "{{ project_name }}"
        state: opened
        nodes_state: started
        nodes_strategy: one_by_one

    - name: Collect the nodes inventory
      davidban77.gns3.gns3_nodes_inventory:
        url: "{{ gns3_url }}"
        project_name: "{{ project_name }}"
      register: nodes_inventory

    - name: Pause for 2 minutes while nodes stsrt
      ansible.builtin.pause:
        minutes: 2

- name: "Plays to run for each inventory host"
  hosts: all
  gather_facts: false
  roles:
    - basic_iosv_telnet
