---
- name: Configure hostname using Telnet connection
  gather_facts: false
  hosts: all
#  vars:
#    ansible_connection: ansible.netmiko_telnet
  tasks:
    - name: Configure hostname
#      cisco.ios.ios_command:
#        commands:
#          - hostname {{ inventory_hostname }}
      

      ansible.netcommon.telnet:
        port: '{{ hostvars[inventory_hostname].port }}'
        password_prompt: ''
        login_prompt: ''
        send_newline: true
        prompts:
          - '[>#?]'
        command:
          - terminal length 0
          - configure terminal
          - hostname {{ inventory_hostname }}
          - exit
          - copy running-config startup-config
          - startup-config
