---
- name: Configure hostname using Telnet connection
  gather_facts: false
  hosts: all
  tasks:
    - name: Configure hostname
      telnetX:
        port: '{{ hostvars[inventory_hostname].port }}'
        timeout: 5
        send_carriage_return: true
        prompts:
          - '[>#]'
        command:
          - configure terminal
          - hostname {{ inventory_hostname }}

    - name: Configure con 0
      telnetX:
        port: '{{ hostvars[inventory_hostname].port }}'
        timeout: 5
        send_carriage_return: true
        prompts:
          - '[>#]'
        command:
          - no ip domain-lookup
          - service password-encryption
          - line con 0
          - exec-timeout 0 0
          - privilege level 15
          - logging synchronous
          - length 60
          - width 200
          - exit

    - name: Configure banners
      telnetX:
        port: '{{ hostvars[inventory_hostname].port }}'
        timeout: 5
        send_carriage_return: true
        prompts:
          - '[>#]'
        command:
          - banner exec $$
          - banner incoming $$
          - banner login $$
          - banner motd $$

    - name: Configure Interfaces - disable MOP / keepalives
      telnetX:
        port: '{{ hostvars[inventory_hostname].port }}'
        timeout: 5
        send_carriage_return: true
        prompts:
          - '[>#]'
        command:
          - interface r g0/0-3
          - no mop enabled
          - no keepalive
          - exit

    - name: Configure SSH
      telnetX:
        port: '{{ hostvars[inventory_hostname].port }}'
        timeout: 5
        send_carriage_return: true
        prompts:
          - '[>#]'
        command:
          - ip domain-name NET.LAB
          - crypto key generate rsa modulus 768
          - username admin password admin
          - line vty 0 4
          - transport input ssh
          - login local
          - exit

    - name: Save Config
      telnetX:
        port: '{{ hostvars[inventory_hostname].port }}'
        timeout: 5
        send_carriage_return: true
        prompts:
          - '[>#]'
        command:
          - copy running-config startup-config
          - "\r"
          - "\r"
