---
- name: Configure hostname using Telnet connection
  gather_facts: false
  hosts: all
  tasks:
    - name: Configure hostname
      telnetX:
        port: '{{ hostvars[inventory_hostname].port }}'
        password_prompt: ''
        login_prompt: ''
        timeout: 5
        send_carriage_return: true
        prompts:
          - '[>#]'
        command:
          - terminal length 0
          - configure terminal
          - hostname {{ inventory_hostname }}
          - exit
          - copy running-config startup-config
          - startup-config
